import PackagePlugin
import Foundation

@main
struct XprojectVersionPlugin: BuildToolPlugin {
    func createBuildCommands(context: PluginContext, target: Target) async throws -> [Command] {
        let versionFile = context.package.directoryURL.appending(path: "VERSION")
        let outputFile = context.pluginWorkDirectoryURL.appending(path: "GeneratedVersion.swift")

        return [
            .buildCommand(
                displayName: "Generate version from VERSION file",
                executable: URL(fileURLWithPath: "/bin/bash"),
                arguments: [
                    "-c",
                    """
                    set -e
                    VERSION=$(cat "\(versionFile.path)" | tr -d '\\n')
                    if [ -z "$VERSION" ]; then
                        echo "Error: VERSION file is empty or missing" >&2
                        exit 1
                    fi
                    if ! echo "$VERSION" | grep -qE '^[0-9]+\\.[0-9]+\\.[0-9]+$'; then
                        echo "Error: VERSION must be a valid semver (e.g., 1.0.0), got: $VERSION" >&2
                        exit 1
                    fi
                    cat > "\(outputFile.path)" << EOF
                    // Auto-generated by XprojectVersionPlugin - do not edit
                    enum GeneratedVersion {
                        static let version = "$VERSION"
                    }
                    EOF
                    """
                ],
                inputFiles: [versionFile],
                outputFiles: [outputFile]
            )
        ]
    }
}
